### ISSUE TITLE
Prototype Pollution using .parse()

### ISSUE THREAD

**Issue by keerok** [wollardj/simple-plist#60]
Hi, There's a prototype pollution vulnerability in .parse() related to the xml that are being parsed in it. In the following example the prototype pollution will affect the length parameter.

```javascript
var plist = require('simple-plist');

var xml = `
<plist version="1.0">
    <key>metadata</key>
    <dict>
      <key>bundle-identifier</key>
      <string>com.company.app</string>
    </dict>
  </plist>`;

console.log(plist.parse(xml));
/**
 * * * * * * * * * * * * * * * * * * * * * * * * * *
 * * * * END OF THE NORMAL CODE EXAMPLE! * * * * * * 
 * * * * * * * * * * * * * * * * * * * * * * * * * * 
 **/


/**
 * * * * * * * * * * * *
 * PROTOTYPE POLLUTION *
 * * * * * * * * * * * *
 **/
var xmlPollution = `
<plist version="1.0">
  <dict>
    <key>__proto__</key>
    <dict>
      <key>length</key>
      <string>polluted</string>
    </dict>
  </dict>
</plist>`;
console.log(plist.parse(xmlPollution).length); // polluted
```

More information about the vulnerability: https://github.com/HoLyVieR/prototype-pollution-nsec18/blob/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf

**Comment by SimenB** [comment]
Since https://github.com/advisories/GHSA-gff7-g5r8-mg8m is a thing now, maybe a ping to @wollardj could get this fixed? 😀

**Comment by Sujay-shetty** [comment]
could you please update plist package to latest version (3.0.5) where this vulnerability is fully fixed?
https://github.com/TooTallNate/plist.js/issues/114

**Comment by wollardj** [comment]
I'm re-opening this for a bit. I want to write some tests to go along with this before I cut a new release, but I won't have time until later this evening.

**Comment by SimenB** [comment]
Seems weird the advisory points to this module if the bug is in an underlying library...

**Comment by wollardj** [comment]
I've just published v1.3.1 to npm (https://www.npmjs.com/package/simple-plist/v/1.3.1) and tagged it as `latest`. Let me know if anyone sees any issues or if any additional audits are failing.

**Comment by srithar21** [comment]
Hi ,

I am getting the same  issue in 1.3.1 version.

https://security.snyk.io/vuln/SNYK-JS-SIMPLEPLIST-2413671
<img width="1098" alt="Screen Shot 2022-04-01 at 10 28 48 AM" src="https://user-images.githubusercontent.com/1001455/161304390-cfd8d7ca-dff0-40ff-b143-9c99753188ce.png">

**Comment by wollardj** [comment]
@srithar21 - I'm not sure how they're able to do that. I attempted to verify their POC by adding a test for it and the underlying [plist.js](https://www.npmjs.com/package/plist) library throws when it detects a `__proto__` key.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/2027935/161389103-0ffca1d9-7b11-4c08-8f54-7fc01d35a75f.png">

Less important, but also a little suspicious, their POC wouldn't work anyway because the first byte is an unexpected ASCII sequence which would have made `simple-plist` attempt to use the binary parser. Since the file isn't binary, their example results in a different error with the message `"Unable to determine format for plist aStringOrBuffer"`.

It's entirely possible if not likely that their POC is suffering from a formatting problem, but it's still worth noting since the POC doesn't appear to be valid.

Happy to be wrong about this if someone can point out something that I might be missing.

**Comment by oanatinus** [comment]
I wonder if you need to close this GitHub issue in order to trigger the various vulnerability databases to "recheck" the vulnerability...

**Comment by elopezanaya** [comment]
Hello,  does someone know the status of this issue?, it seems like it was already solved , but this issue still is open, and in all CVE references is marked as not patched

**Comment by MaeveOReilly** [comment]
`npm audit` still listing it as open with no patch for me; I'm guessing @oanatinus is correct and this issue needs to be closed?

**Comment by oanatinus** [comment]
@wollardj what do you think, do you want to try closing this issue to see if that triggers the vulnerability databases to mark 1.3.1 as the fixed version?

**Comment by wollardj** [comment]
It's worth a shot

**Comment by brice-noowu** [comment]
Still an issue here, npm audit still listing it as open with no patch

**Comment by darakian** [comment]
> It's worth a shot

In the future give us a shout over at https://github.com/github/advisory-database/ if we're out of date 😉
