### ISSUE TITLE
Read from buffer?

### ISSUE THREAD

**Issue by jasonc624** [wollardj/simple-plist#64]
I cannot seem to parse utf8 encoded string (from buffer) using plist.readFileSync. Is this currently possible?

**Comment by wollardj** [comment]
Sorry for the exceptionally delayed reply, but as I'm sure you've already discovered, the answer is no. Under the hood, `readFileSync` is passing the argument into `fs.readFileSync` (see [here](https://github.com/wollardj/simple-plist/blob/main/src/readFileSync.ts#L5)) which wouldn't take a buffer either. However, you can pass descriptor representing an already open file if you'd like.

The `parse` function is probably what you're after since that is designed to accept a buffer, though the encoding still might throw you off.
